export const ALL_PART_REQUEST = "ALL_PART_REQUEST";
export const ALL_PART_SUCCESS = "ALL_PART_SUCCESS";
export const ALL_PART_FAIL = "ALL_PART_FAIL";

export const ADMIN_PART_REQUEST = "ADMIN_PART_REQUEST";
export const ADMIN_PART_SUCCESS = "ADMIN_PART_SUCCESS";
export const ADMIN_PART_FAIL = "ADMIN_PART_FAIL";

export const NEW_PART_REQUEST = "NEW_PART_REQUEST";
export const NEW_PART_SUCCESS = "NEW_PART_SUCCESS";
export const NEW_PART_RESET = "NEW_PART_RESET";
export const NEW_PART_FAIL = "NEW_PART_FAIL";

export const UPDATE_PART_REQUEST = "UPDATE_PART_REQUEST";
export const UPDATE_PART_SUCCESS = "UPDATE_PART_SUCCESS";
export const UPDATE_PART_RESET = "UPDATE_PART_RESET";
export const UPDATE_PART_FAIL = "UPDATE_PART_FAIL";

export const DELETE_PART_REQUEST = "DELETE_PART_REQUEST";
export const DELETE_PART_SUCCESS = "DELETE_PART_SUCCESS";
export const DELETE_PART_RESET = "DELETE_PART_RESET";
export const DELETE_PART_FAIL = "DELETE_PART_FAIL";

export const PART_DETAILS_REQUEST = "PART_DETAILS_REQUEST";
export const PART_DETAILS_SUCCESS = "PART_DETAILS_SUCCESS";
export const PART_DETAILS_FAIL = "PART_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
