export const NEW_TEST_REQUEST = "NEW_TEST_REQUEST";
export const NEW_TEST_SUCCESS = "NEW_TEST_SUCCESS";
export const NEW_TEST_FAIL = "NEW_TEST_FAIL";

export const ALL_TEST_REQUEST = "ALL_TEST_REQUEST";
export const ALL_TEST_SUCCESS = "ALL_TEST_SUCCESS";
export const ALL_TEST_FAIL = "ALL_TEST_FAIL";

export const DELETE_TEST_REQUEST = "DELETE_TEST_REQUEST";
export const DELETE_TEST_SUCCESS = "DELETE_TEST_SUCCESS";
export const DELETE_TEST_FAIL = "DELETE_TEST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";